version: '3'
services:
  minecraft-server:
    container_name: minecraft-server
    build:
      context: .
      dockerfile: .docker/minecraft/Dockerfile
    image: minecraft-server
    ports:
      - 25565:25565
    volumes:
      - storage/world:/srv/minecraft/world
  app:
    container_name: minecraft-server-app
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    image: minecraft-server-app
    ports:
      - 8000:80
    volumes:
      - .:/srv/app
